M48
; DRILL file KiCad 10.0.1 date 2026-06-09T10:09:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-09T10:09:58-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X104.105Y-123.61
X104.105Y-129.39
T2
X150.0Y-59.0
X150.0Y-62.0
X182.0Y-62.5
X182.0Y-65.5
M30
